### ISSUE TITLE
MIME type issue with sitemap.xsl

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-contrib/xmlsitemap#24]
"Resource interpreted as Stylesheet but transferred with MIME type application/xml: "http://localhost/backdrop/sitemap.xsl".

sitemap.xml line 2:
<?xml-stylesheet type="text/xsl" href="//localhost/backdrop/sitemap.xsl"?>

Happened on Chrome 54.0.28 on "/sitemap.xml" page.

**Comment by laryn** [comment]
Cannot reproduce.
