### ISSUE TITLE
XML Sitemap Node Tests

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-contrib/xmlsitemap#28]
135 passes, 5 fails, 0 exceptions, and 26 debug messages

All failures in xmlsitemap_node.test

**Comment by alexfinnarn** [comment]
The problem appears in the testCron() method when `$types = xmlsitemap_get_link_type_enabled_bundles('node')` doesn't return anything. The newly created nodes don't get processed and so the assertions fail. This seems like an issue with variables or the database, but not indicative of a major bug in the module.

**Comment by alexfinnarn** [comment]
In #57, the code changed to not create sitemap links on node update but rather queue those for cron. the tests need to be updated to relfect that change.

**Comment by jenlampton** [comment]
I'm seeing something similar in https://github.com/backdrop-contrib/xmlsitemap/issues/88

**Comment by quicksketch** [comment]
The tests have been updated in https://github.com/backdrop-contrib/xmlsitemap/pull/107 to now check for a initial access of 0 on node save, then reflect an updated access value after running cron.
