### ISSUE TITLE
JS related problems

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/xmlsitemap#36]
Hi!
There are many different JS related problems arise in Backdrop because of submodule **XML sitemap node**.

Please look only at one issue: https://github.com/backdrop/backdrop-issues/issues/2627

**Comment by alexfinnarn** [comment]
These errors come from a legacy Drupal function that needed converting to Backdrop.

**Comment by alexfinnarn** [comment]
Thanks for reporting @bd0bd! Fix merged in.
