### ISSUE TITLE
xmlsitemap drush commands break drush

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/xmlsitemap#38]
Should we remove or comment them out until they are working?

**Comment by alexfinnarn** [comment]
I'm a glass half-full kind of guy so I'd say comment them out for now. I have no idea what the state of drush in Backdrop is, though. That PR looks like it deletes the drush commands entirely.

**Comment by jenlampton** [comment]
You're right, I must have been drinking the crazy sauce when I added that commit message :)  I'll comment them out and push up an update.

**Comment by alexfinnarn** [comment]
Pushed in 1.x-1.0.1 release.
