### ISSUE TITLE
Where is the 1.x-1.x branch?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/xmlsitemap#39]
Hi!  I'd like to do some work on xmlsitemap, but I can't find the right branch in the repo. Can we define 1.x-1.x (and set that to the default branch) and maybe cleanup/remove all the others that are not active development branches?

**Comment by alexfinnarn** [comment]
That all sounds fine to me. I wasn't really aware of the branch conventions. Maybe that info should be added to https://github.com/backdrop-ops/contrib/pull/199? 

I created the 1.x-1.x branch, but I can't set it to default on account of permissions. I've added the "help wanted" label as it seems to fit the bill here. Not sure if it is a "backdrop-ops/contrib" issue...

**Comment by jenlampton** [comment]
> Maybe that info should be added to backdrop-ops/contrib#199?

An excellent idea :)

> I created the 1.x-1.x branch, but I can't set it to default on account of permissions.

I have fixed this for you, you are an admin on the project now. (we also have an open issue about using the API to properly set permissions when people move their repo into the Backdrop group.)

**Comment by alexfinnarn** [comment]
Cool, thanks. I went ahead and made the "1.x-1.x" branch the default branch for this repo. I think this answers your question/need?

**Comment by jenlampton** [comment]
Yes, thank you!
